app = "qanda"  # or use the exact name of your app from Fly.io!

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "10001"

[[services]]
  internal_port = 10001
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443